services:

  wordpress:
    image: wordpress
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: pass
      WORDPRESS_DB_NAME: cabinetfamillia
    volumes:
      - wordpress:/var/www/html
      - ./wp-content/themes/cabinetfamillia:/var/www/html/wp-content/themes/cabinetfamillia

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: cabinetfamillia
    volumes:
      - db:/var/lib/mysql
      
volumes:
  wordpress:
  db: